### ISSUE TITLE
mejora - ingresar fecha de nacimiento y validarla

### ISSUE THREAD

**Issue by Eugemo** [rmoyano/grupo-e#1]
se propone como mejora el ingreso de una fecha de nacimiento y la validacion de la misma, con un mensaje que indique si es valida o no la fecha.
`import time
 
def validateDateEs(date):
    """
    Funcion para validar una fecha en formato:
        dd/mm/yyyy, dd/mm/yy, d/m/yy, dd/mm/yyyy hh:mm:ss, dd/mm/yy hh:mm:ss, d/m/yy h:m:s
    """
    for format in ['%d/%m/%Y', '%d/%m/%y', '%d/%m/%Y %H:%M:%S', '%d/%m/%y %H:%M:%S']:
        try:
            result = time.strptime(date, format)
            return True
        except:
            pass
    return False
 
entrada = input("Ingrese fecha de Nacimiento en formato dd/mm/aa: ")
 
if validateDateEs(entrada):
    print 'Fecha correcta'
else:
    print 'Fecha incorrecta' `

**Comment by rmoyano** [comment]
Perfecto, asignado.
