### ISSUE TITLE
un comentario no más

### ISSUE THREAD

**Issue by eamanu** [rmoyano/grupo-e#7]
Hace unos días me crucé con este mismo problema 
(tener que jugar con diferentes formatos de fechas,
 que solo es conocido en tiempo de ejecución). Lo pensé
como regex, pero la expresión se estaba volviendo demasiado
grande y poco mantenible. Por lo que opté por ir
escribiendo try except, try except lo cual queda muy feo, 
pero funciona. Esta solución está espectacular, no se me
ocurrió y tiene el mismo funcionamiento que ir encadenando los try.

Muy buena, :)

https://github.com/rmoyano/grupo-e/blob/e78b87fd00f197aff309dafab2a6f6d9a16dc94d/persona.py#L13

cc: @michysantillan @mnrios1997 @Eugemo @rmoyano

**Comment by Eugemo** [comment]
gracias :)
